[package]
name = "embedded-test-macros"
description = "proc-macros for the embedded-test crate"
version = "0.8.2"
edition = "2021"
repository = "https://github.com/probe-rs/embedded-test"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.79"
proc-macro-error3 = { version = "=3.1.0", default-features = false } # disable syn-error feature to avoid a duplicate/mismatched syn dependency
quote = "1.0.35"
syn = { version = "3.0.3", features = ["extra-traits", "full"] }
darling = "0.24.0"

[features]
embassy = [] # any embassy version selected
embassy-09 = ["embassy"]
embassy-010 = ["embassy"]
external-executor = ["embassy"]
ariel-os = []
std = []
